services:
  web:
    image: ryyytay/snowboardeshop:latest
    ports:
      - "8080:8080"
    environment:
      - Cloudinary:CloudName=dvj1vfj72
      - Cloudinary:ApiKey=736566511122155
      - Cloudinary:ApiSecret=6fXX2hh6wPFzpnfaMAOfIiP5L4I
      - StripeSettings:PublishableKey=pk_test_51PjbvbK1Y6bCNrVWBGIfoKJC3FLlkq6kcvsxta0vBTUdDtZGiE7RPtDuy8Eg8dQnyd5wngKIxlPyqbiCM6sXWAHf002SU22wLK
      - StripeSettings:SecretKey=sk_test_51PjbvbK1Y6bCNrVWbjUR8qDpMJAhLq6tZLjzufJH4gBlevuZf9rekMOs4F5Me6EblW0SVhJSkAsJeE5zHY5ntnkn00ojiUVTG3
      - StripeSettings:WhSecret=whsec_bb437a4d906113503d73374aff3132a9e3f9c89e7a56de0b0c3e0666ccb87210
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
