version: '3.8'
services:
  web:
    image: ryyytay/snowboardeshop:latest
    ports:
      - "8080:8080"
    environment:
      - Cloudinary:CloudName=dvj1vfj72
      - Cloudinary:ApiKey=736566511122155
      - Cloudinary:ApiSecret=6fXX2hh6wPFzpnfaMAOfIiP5L4I
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
